# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=19)),
                ('descrizione', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_entrata', models.BooleanField(default=False)),
                ('fissa', models.BooleanField(default=False)),
                ('conto_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoPersonale.Conto')),
            ],
        ),
    ]
