# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0003_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='conto',
            name='scelta_tipo',
            field=models.CharField(choices=[('CC', 'Conto Corrente'), ('CR', 'Conto Risparmio')], default='CC', max_length=2),
        ),
    ]
