# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0004_auto_20180522_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conto',
            old_name='scelta_tipo',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='transazione',
            name='fissa',
        ),
        migrations.RemoveField(
            model_name='transazione',
            name='in_entrata',
        ),
        migrations.AddField(
            model_name='transazione',
            name='periodicita',
            field=models.CharField(choices=[('FIS', 'Fissa'), ('VAR', 'Variabile')], default='VAR', max_length=3),
        ),
        migrations.AddField(
            model_name='transazione',
            name='tipo',
            field=models.CharField(choices=[('IN', 'In Entrata'), ('OUT', 'In Uscita')], default='OUT', max_length=3),
        ),
    ]
