# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0005_auto_20180522_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transazione',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
