# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0006_auto_20180522_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='aggiornaConto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conto_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoPersonale.Conto')),
                ('transazione_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contoPersonale.Transazione')),
            ],
        ),
    ]
