# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0007_aggiornaconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggiornaconto',
            name='conto_ref',
        ),
        migrations.RemoveField(
            model_name='aggiornaconto',
            name='transazione_ref',
        ),
        migrations.DeleteModel(
            name='aggiornaConto',
        ),
    ]
