# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0008_auto_20180523_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='transazione',
            name='saldata',
            field=models.BooleanField(default=False),
        ),
    ]
