# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0009_transazione_saldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazione',
            name='saldata',
        ),
    ]
