# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contoPersonale', '0015_auto_20180528_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conto',
            old_name='saldo',
            new_name='saldo_iniziale',
        ),
    ]
